rbac:
 create: true
controller:
  service:
    type: NodePort
    #type: LoadBalancer
    #loadBalancerIP: 132.206.37.38
    #annotations:
    #  metallb.universe.tf/allow-shared-ip: 6f48f0
  kind: DaemonSet
  hostNetwork: true
  config:
    # Allow POSTs of upto 64MB, for large notebook support.
    proxy-body-size: 64m
